services:
  db:
    image: mysql:8.4
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: ${TZ}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
      #設定ファイルをコンテナ内にマウント
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    healthcheck:
      #dbが起動したか確認
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${MYSQL_USER}", "-p${MYSQL_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
      #Linuxユーザの権限問題を解消するためにUID/GIDを引数として渡す(引数が空なら右側の値)
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USERNAME=${USERNAME:-appuser}
        - GROUPNAME=${GROUPNAME:-appgroup}
    container_name: fastapi_backend
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=dev
      - SECRET_KEY=${SECRET_KEY}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - DATABASE_URL=mysql+aiomysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST:-db}:${MYSQL_PORT:-3306}/${MYSQL_DATABASE}
    depends_on:
      db:
        #dbがhealthyになるまで起動を待つ
        condition: service_healthy

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USERNAME=${USERNAME:-appuser}
        - GROUPNAME=${GROUPNAME:-appgroup}
    container_name: react_frontend
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      #全ファイルが/appにマウントされる
      - ./frontend:/app
      #自分の環境をコンテナ内に持ち込ませないため(バイナリの互換性)
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
      #Viteがコンテナ外からのアクセスを受け付けるための設定
      - HOST=0.0.0.0
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  db_data: